# -*- coding: utf-8 -*-
"""efficientnet_lesongnhatquyen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKp6yepW7BFzKQs45Ilb3tC5kP40YQD9

# Face Attributes Recognition with EfficientNet

Notebook này demo cách dùng **EfficientNet-B0** làm backbone để nhận diện đa thuộc tính khuôn mặt:
- Emotion (nếu bạn cộng thêm FER2013)
- Age (theo nhóm tuổi)
- Gender
- Race / Ethnicity

Chúng ta sẽ:
1. Hướng dẫn lấy dataset từ Kaggle (UTKFace, FairFace, FER2013)
2. Tạo Dataset đọc UTKFace (có age, gender, race trong tên file)
3. Dùng EfficientNet-B0 pretrained làm feature extractor
4. Thêm 3 head: age, gender, race
5. Train 5 epoch → lưu model tốt nhất

> Lưu ý: EfficientNet gốc không có sẵn trong `torchvision` bản cũ, nên ở đây mình dùng thư viện `timm` (PyTorch Image Models). Trên Colab chỉ cần `!pip install timm`.
"""

# ! pip install -q kaggle

import os
from google.colab import drive
drive.mount('/content/drive/')

path = r'/content/drive/MyDrive/Colab Notebooks/dataset'
os.listdir(path)

path = r'/content/drive/MyDrive/Colab Notebooks/dataset/utkface-new'
os.listdir(path)

path = r'/content/drive/MyDrive/Colab Notebooks/dataset/fer2013'
os.listdir(path)

!mkdir -p ~/.kaggle

!mv kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d msambare/fer2013 -p "/content/drive/MyDrive/Colab Notebooks/dataset" --force

!unzip "/content/drive/MyDrive/Colab Notebooks/dataset/fer2013.zip" -d "/content/drive/MyDrive/Colab Notebooks/dataset/fer2013"

!kaggle datasets download -d jangedoo/utkface-new -p "/content/drive/MyDrive/Colab Notebooks/dataset" --force

!unzip "/content/drive/MyDrive/Colab Notebooks/dataset/utkface-new.zip" -d "/content/drive/MyDrive/Colab Notebooks/dataset/utkface-new"

!ls "/content/drive/MyDrive/Colab Notebooks/dataset/utkface-new"

# 2. Import thư viện
import glob
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T

# cài timm nếu chưa có (bạn chạy dòng này trên Colab):
# !pip install timm
import timm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

"""## 3. Dataset UTKFace

Tên file mẫu: `22_0_0_20170104010223288.jpg.chip.jpg`
- 22 → age
- 0 → gender (0=male, 1=female)
- 0 → race (0: White, 1: Black, 2: Asian, 3: Indian, 4: Others)

Ta sẽ map tuổi thành 5 nhóm để dễ học.
"""

from torch.utils.data import Dataset
from PIL import Image
import os
import torch

def age_to_group5(age: int) -> int:
    """
    Chia tuổi thành 5 nhóm:
    0: 0-18
    1: 19-30
    2: 31-45
    3: 46-60
    4: 61+
    """
    if age <= 18:
        return 0
    elif age <= 30:
        return 1
    elif age <= 45:
        return 2
    elif age <= 60:
        return 3
    else:
        return 4

class UTKFaceDataset(Dataset):
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform
        self.samples = []  # (path, age_group, gender, race)

        for fname in os.listdir(root):
            if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
                continue

            parts = fname.split("_")
            if len(parts) < 4:
                continue

            try:
                age = int(parts[0])
                gender = int(parts[1])   # 0 hoặc 1
                race = int(parts[2])     # 0..4
            except ValueError:
                continue

            age_group = age_to_group5(age)  # ⭐ map về 0..4

            path = os.path.join(root, fname)
            self.samples.append((path, age_group, gender, race))

        print(f"[UTKFaceDataset] {root} -> {len(self.samples)} ảnh hợp lệ")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, age_group, gender, race = self.samples[idx]

        img = Image.open(path).convert("RGB")
        if self.transform is not None:
            img = self.transform(img)

        return {
            "image": img,
            "age_cls": torch.tensor(age_group, dtype=torch.long),  # ⭐ 0..4
            "gender": torch.tensor(gender, dtype=torch.long),      # 0..1
            "race": torch.tensor(race, dtype=torch.long),          # 0..4
        }

"""# 3.1. Transform và DataLoader"""

train_tfms = T.Compose([
    T.Resize((224, 224)),  # EfficientNet-B0 dùng 224x224
    T.RandomHorizontalFlip(),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_tfms = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Đổi path theo máy bạn
train_dir = "/content/drive/MyDrive/Nhom1_Py/Dataset/utkface-new/train"
val_dir = "/content/drive/MyDrive/Nhom1_Py/Dataset/utkface-new/val"

if os.path.exists(train_dir):
    train_ds = UTKFaceDataset(train_dir, transform=train_tfms)
    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=2)
else:
    train_ds = None
    train_loader = None

if os.path.exists(val_dir):
    val_ds = UTKFaceDataset(val_dir, transform=val_tfms)
    val_loader = DataLoader(val_ds, batch_size=32, shuffle=False, num_workers=2)
else:
    val_ds = None
    val_loader = None

train_ds

"""## 4. EfficientNet-B0 Multi-head

Ta sẽ dùng `timm.create_model('efficientnet_b0', pretrained=True)` → lấy feature dimension → tách 3 head.

Số lớp:
- Age: 5 lớp
- Gender: 2 lớp
- Race: 5 lớp

"""

class EfficientNetMultiHead(nn.Module):
    def __init__(self, num_age=5, num_gender=2, num_race=5):
        super().__init__()
        self.backbone = timm.create_model("efficientnet_b0", pretrained=True, num_classes=0, global_pool="avg")
        feat_dim = self.backbone.num_features  # thường là 1280
        # shared head
        self.shared_fc = nn.Sequential(
            nn.Linear(feat_dim, 512),
            nn.ReLU(),
        )
        self.age_head = nn.Linear(512, num_age)
        self.gender_head = nn.Linear(512, num_gender)
        self.race_head = nn.Linear(512, num_race)

    def forward(self, x):
        x = self.backbone(x)
        x = self.shared_fc(x)
        age_logits = self.age_head(x)
        gender_logits = self.gender_head(x)
        race_logits = self.race_head(x)
        return age_logits, gender_logits, race_logits

model = EfficientNetMultiHead().to(device)
model

"""## 5. Hàm train / eval 5 epoch

Tương tự VGG và ResNet: tổng loss = loss_age + loss_gender + loss_race.
"""

def train_one_epoch(model, loader, optimizer, ce_age, ce_gender, ce_race):
    model.train()
    running_loss = 0.0
    for batch in loader:
        imgs = batch['image'].to(device)
        age = batch['age_cls'].to(device)
        gender = batch['gender'].to(device)
        race = batch['race'].to(device)

        optimizer.zero_grad()
        age_logits, gender_logits, race_logits = model(imgs)

        loss_age = ce_age(age_logits, age)
        loss_gender = ce_gender(gender_logits, gender)
        loss_race = ce_race(race_logits, race)
        loss = loss_age + loss_gender + loss_race
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * imgs.size(0)
    return running_loss / len(loader.dataset)

@torch.no_grad()
def eval_one_epoch(model, loader, ce_age, ce_gender, ce_race):
    model.eval()
    total = 0
    run_loss = 0.0
    correct_age = 0
    correct_gender = 0
    correct_race = 0
    for batch in loader:
        imgs = batch['image'].to(device)
        age = batch['age_cls'].to(device)
        gender = batch['gender'].to(device)
        race = batch['race'].to(device)

        age_logits, gender_logits, race_logits = model(imgs)

        loss_age = ce_age(age_logits, age)
        loss_gender = ce_gender(gender_logits, gender)
        loss_race = ce_race(race_logits, race)
        loss = loss_age + loss_gender + loss_race
        run_loss += loss.item() * imgs.size(0)

        _, age_pred = age_logits.max(1)
        _, gender_pred = gender_logits.max(1)
        _, race_pred = race_logits.max(1)

        correct_age += (age_pred == age).sum().item()
        correct_gender += (gender_pred == gender).sum().item()
        correct_race += (race_pred == race).sum().item()
        total += imgs.size(0)
    avg_loss = run_loss / len(loader.dataset)
    age_acc = correct_age / total
    gender_acc = correct_gender / total
    race_acc = correct_race / total
    return avg_loss, age_acc, gender_acc, race_acc

import os

bad_files = []
root = train_dir  # hoặc val_dir

for fname in os.listdir(root):
    if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
        continue
    parts = fname.split("_")
    if len(parts) < 4:
        bad_files.append(fname)
        continue
    try:
        age = int(parts[0])
        gender = int(parts[1])
        race = int(parts[2])
    except ValueError:
        bad_files.append(fname)

print("Số file lỗi:", len(bad_files))
print("Ví dụ:", bad_files[:10])

train_ds = UTKFaceDataset(train_dir, transform=train_tfms)
val_ds   = UTKFaceDataset(val_dir, transform=val_tfms)

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=32, shuffle=False, num_workers=2)

def train_one_epoch(model, loader, optimizer, ce_age, ce_gender, ce_race):
    model.train()
    running_loss = 0.0

    for i, batch in enumerate(loader):
        imgs = batch['image'].to(device)
        age  = batch['age_cls'].to(device)
        gender = batch['gender'].to(device)
        race   = batch['race'].to(device)

        age_logits, gender_logits, race_logits = model(imgs)

        if i == 0:  # in thử 1 batch đầu
            print("age_logits shape:", age_logits.shape)       # (N, C_age)
            print("gender_logits shape:", gender_logits.shape) # (N, C_gender)
            print("race_logits shape:", race_logits.shape)     # (N, C_race)
            print("max age label:", age.max().item())
            print("max gender label:", gender.max().item())
            print("max race label:", race.max().item())

        loss_age    = ce_age(age_logits, age)
        loss_gender = ce_gender(gender_logits, gender)
        loss_race   = ce_race(race_logits, race)

        loss = loss_age + loss_gender + loss_race

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * imgs.size(0)

    return running_loss / len(loader.dataset)

from torch.utils.data import DataLoader

batch = next(iter(train_loader))

imgs = batch['image'].to(device)
age = batch['age_cls'].to(device)
gender = batch['gender'].to(device)
race = batch['race'].to(device)

print("imgs shape:", imgs.shape)
print("age shape:", age.shape)
print("gender shape:", gender.shape)
print("race shape:", race.shape)

with torch.no_grad():
    age_logits, gender_logits, race_logits = model(imgs)

print("age_logits shape:", age_logits.shape)
print("gender_logits shape:", gender_logits.shape)
print("race_logits shape:", race_logits.shape)

print("max age label:", age.max().item())
print("max gender label:", gender.max().item())
print("max race label:", race.max().item())
print("unique gender:", age.unique()[:10])
print("unique race:", race.unique()[:10])

import os

class UTKFaceDataset(Dataset):
    def __init__(self, root, transform=None):
        self.transform = transform
        all_samples = build_samples_somehow(root)  # chỗ bạn đang tạo list (path, age_group, gender, race)

        valid_samples = []
        for path, age_group, gender, race in all_samples:
            if os.path.exists(path):
                valid_samples.append((path, age_group, gender, race))
            else:
                print("⚠️ Bỏ qua file không tồn tại:", path)

        self.samples = valid_samples
        print("Tổng số ảnh dùng được:", len(self.samples))

    def __getitem__(self, idx):
        path, age_group, gender, race = self.samples[idx]
        img = Image.open(path).convert("RGB")
        if self.transform is not None:
            img = self.transform(img)
        return {
            "image": img,
            "age_cls": age_group,
            "gender": gender,
            "race": race,
        }

    def __len__(self):
        return len(self.samples)

from PIL import Image, UnidentifiedImageError
import random, os

def __getitem__(self, idx):
    path, age_group, gender, race = self.samples[idx]

    if not os.path.exists(path):
        print("⚠️ File mất:", path)
        new_idx = random.randint(0, len(self.samples) - 1)
        return self.__getitem__(new_idx)

    img = Image.open(path).convert("RGB")
    if self.transform is not None:
        img = self.transform(img)

    return {
        "image": img,
        "age_cls": age_group,
        "gender": gender,
        "race": race,
    }

# 6. Train 5 epoch
num_epochs = 5
ce_age = nn.CrossEntropyLoss()
ce_gender = nn.CrossEntropyLoss()
ce_race = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

best_val_loss = float('inf')
best_state = None

if train_loader is not None and val_loader is not None:
    for epoch in range(num_epochs):
        train_loss = train_one_epoch(model, train_loader, optimizer, ce_age, ce_gender, ce_race)
        val_loss, age_acc, gender_acc, race_acc = eval_one_epoch(model, val_loader, ce_age, ce_gender, ce_race)
        print(f"Epoch {epoch+1}/{num_epochs} | train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | age_acc={age_acc:.3f} | gender_acc={gender_acc:.3f} | race_acc={race_acc:.3f}")
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = model.state_dict()
else:
    print("⚠️ Chưa tìm thấy data. Hãy tải UTKFace và đặt vào data/utkface/train, data/utkface/val")

# 7. Lưu model tốt nhất
if best_state is not None:
    os.makedirs("checkpoints", exist_ok=True)
    torch.save(best_state, "/content/drive/MyDrive/Nhom1_Py/efficientnet_multihead_best.pth")
    print("✅ Đã lưu /content/drive/MyDrive/Nhom1_Py/efficientnet_multihead_best.pth")
else:
    print("⚠️ Không có model để lưu (có thể chưa train do thiếu dữ liệu)")

model = EfficientNetMultiHead().to(device)

ckpt_path = "/content/drive/MyDrive/Nhom1_Py/efficientnet_multihead_best.pth"
state_dict = torch.load(ckpt_path, map_location=device)
model.load_state_dict(state_dict)
model.eval()

print("✅ Đã load lại model từ", ckpt_path)

img_tfms = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]),
])

# import os
# folder = "/content/drive/MyDrive/Nhom1_Py/Dataset/sample_img"
# os.listdir(folder)

import os
import torch
import torch.nn.functional as F
from PIL import Image
import matplotlib.pyplot as plt

# class labels
age_classes = ["age_0", "age_1", "age_2", "age_3", "age_4"]
gender_classes = ["male", "female"]
race_classes = ["White", "Black", "Asian", "Indian", "Others"]

def predict_folder(folder_path, model, device, img_tfms):
    results = []

    valid_ext = (".jpg", ".jpeg", ".png", ".bmp")
    files = [f for f in sorted(os.listdir(folder_path)) if f.lower().endswith(valid_ext)]

    if len(files) == 0:
        print("⚠️ Không có file ảnh:", folder_path)
        return []

    print(f"🔍 Phát hiện {len(files)} ảnh, bắt đầu dự đoán...\n")

    for fname in files:
        img_path = os.path.join(folder_path, fname)

        # đọc ảnh
        img = Image.open(img_path).convert("RGB")
        x = img_tfms(img).unsqueeze(0).to(device)

        # dự đoán
        with torch.no_grad():
            age_logits, gender_logits, race_logits = model(x)

            age_prob    = F.softmax(age_logits, dim=1)[0]
            gender_prob = F.softmax(gender_logits, dim=1)[0]
            race_prob   = F.softmax(race_logits, dim=1)[0]

            age_idx    = age_prob.argmax().item()
            gender_idx = gender_prob.argmax().item()
            race_idx   = race_prob.argmax().item()

        # ==========================
        # HIỂN THỊ ẢNH
        # ==========================
        plt.imshow(img)
        plt.axis("off")
        plt.title(f"{fname}")
        plt.show()

        # In kết quả
        print("Ảnh:", fname)
        print("  Age    :", age_classes[age_idx],      "| probs =", age_prob.cpu().numpy())
        print("  Gender :", gender_classes[gender_idx], "| probs =", gender_prob.cpu().numpy())
        print("  Race   :", race_classes[race_idx],    "| probs =", race_prob.cpu().numpy())
        print("---------------------------------------------")

        # lưu vào list
        results.append({
            "image_path": img_path,
            "age_idx": age_idx,
            "gender_idx": gender_idx,
            "race_idx": race_idx,
            "age_prob": age_prob.cpu().numpy(),
            "gender_prob": gender_prob.cpu().numpy(),
            "race_prob": race_prob.cpu().numpy(),
        })

    print("\n✅ Hoàn thành dự đoán tất cả ảnh.")
    return results


# --- GỌI HÀM ---
folder_path = "/content/drive/MyDrive/Nhom1_Py/Dataset/sample_img"
results = predict_folder(folder_path, model, device, img_tfms)