# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuseHS5qtbk3M3NzlAFZAsWdFl36lqTj
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

"""# KNN là thuật toán phân loại dựa trên độ tương đồng. Khi dự đoán một điểm mới, KNN sẽ tìm K điểm gần nhất trong tập dữ liệu và lấy lớp chiếm đa số để dự đoán. Thuật toán không huấn luyện mà chỉ dùng khoảng cách để so sánh.

# KNN (K-Nearest Neighbors – Classification/Regression)

## 1. Dự đoán bệnh tiểu đường

Input: tuổi, cân nặng, mức đường huyết, huyết áp.

KNN sẽ tìm các bệnh nhân gần nhất trong dữ liệu huấn luyện để đoán xem người mới có khả năng bị tiểu đường hay không.
"""

# 1) Đọc dữ liệu
df = pd.read_csv("diabetes_knn.csv")
X = df[["Age", "Weight", "Glucose", "BloodPressure"]]
y = df["Diabetes"]

# 2) Chia tập train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# 3) Tạo pipeline: Chuẩn hóa (StandardScaler) + KNN(k=5)
model = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5, weights="distance"))
])

# 4) Huấn luyện
model.fit(X_train, y_train)

# 5) Đánh giá
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Ví dụ bệnh nhân mới:
new_patient = pd.DataFrame([{
    "Age": 45,
    "Weight": 72,       # kg
    "Glucose": 145,     # mg/dL
    "BloodPressure": 88 # mmHg (tâm trương)
}])

proba = model.predict_proba(new_patient)[0][1]  # xác suất bị tiểu đường (class=1)
pred  = model.predict(new_patient)[0]

print("Predicted label (0=No, 1=Yes):", int(pred))
print("Probability of Diabetes:", round(proba, 3))

param_grid = {
    "knn__n_neighbors": [3,5,7,9,11],
    "knn__weights": ["uniform", "distance"],
    "knn__p": [1,2]  # Manhattan vs Euclidean
}

grid = GridSearchCV(model, param_grid, cv=5, n_jobs=-1)
grid.fit(X, y)
print("Best params:", grid.best_params_)
print("Best CV score:", grid.best_score_)

"""## 2. Nhận diện chữ viết tay (MNIST dataset)

Input: ảnh chữ số viết tay (0–9).

KNN tìm những ảnh gần nhất trong tập huấn luyện.

Nếu phần lớn hàng xóm là số 8 → mẫu mới được dự đoán là số 8.

### Cách 1 — Dùng Keras (tiện, nhanh)
"""

from tensorflow.keras.datasets import mnist
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from PIL import Image

# 1) Tải MNIST (60k train, 10k test)
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 2) Chuyển ảnh 28x28 -> vector 784 & chuẩn hóa [0,1]
X_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0
X_test  = x_test.reshape(-1, 28*28).astype("float32") / 255.0

# (Tùy chọn) Dùng subset cho nhanh: ~10k mẫu
X_sub, _, y_sub, _ = train_test_split(X_train, y_train, train_size=10000, stratify=y_train, random_state=42)

# 3) KNN
knn = KNeighborsClassifier(n_neighbors=3, weights="distance", n_jobs=-1)
knn.fit(X_sub, y_sub)

# 4) Đánh giá
y_pred = knn.predict(X_test[:2000])  # chấm 2k mẫu cho nhanh
print("Accuracy:", accuracy_score(y_test[:2000], y_pred))
print(classification_report(y_test[:2000], y_pred))

# Lưu 5k ảnh train: 784 cột pixel + 1 cột label
N = 5000
df = pd.DataFrame(X_train[:N])
df["label"] = y_train[:N]
df.to_csv("mnist_5k_flat.csv", index=False)
print("Đã lưu mnist_5k_flat.csv")

import matplotlib.pyplot as plt

# Lấy 1 ảnh số viết tay từ tập test
sample_img = x_test[0].reshape(28,28) * 255
plt.imsave("digit.png", sample_img, cmap="gray")

def load_digit_image(path):
    # Đọc ảnh, chuyển grayscale, resize 28x28, scale [0,1]
    img = Image.open(path).convert("L").resize((28,28))
    arr = np.array(img).astype("float32") / 255.0
    return arr.reshape(1, 28*28)

x_new = load_digit_image("digit.png")   # ảnh số viết tay nền trắng/đen
pred = knn.predict(x_new)[0]
proba = knn.predict_proba(x_new).max()
print("Dự đoán:", pred, "| Độ tự tin:", round(proba, 3))

"""### Cách 2 — Dùng OpenML (chuẩn MNIST_784, không cần TensorFlow)"""

from sklearn.datasets import fetch_openml
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# 1) Tải MNIST_784
mnist = fetch_openml("mnist_784", version=1, as_frame=False)  # X: (70000, 784), y: str
X = mnist.data.astype("float32") / 255.0
y = mnist.target.astype(int)

# 2) Chia tập (dùng 12k để demo KNN nhanh)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=12000, test_size=2000, stratify=y, random_state=42
)

# 3) KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3, weights="distance", n_jobs=-1)
knn.fit(X_train, y_train)

# 4) Đánh giá
pred = knn.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))

df = pd.DataFrame(X_train)
df["label"] = y_train
df.to_csv("mnist_subset_train.csv", index=False)
print("Đã lưu mnist_subset_train.csv")

"""### Cách 3 (NHẸ, chạy siêu nhanh) — sklearn.datasets.load_digits (8×8, không phải MNIST 28×28)"""

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

digits = load_digits()  # 1797 ảnh, 8x8 = 64 pixels
X = digits.data / 16.0  # scale [0,1]
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=3, weights="distance")
knn.fit(X_train, y_train)
print("Accuracy:", accuracy_score(y_test, knn.predict(X_test)))